#!/usr/bin/env bash

dothome=~/.dotfiles

yay -S \
	zsh \
	zsh-completions \
	antibody \
	fzf \
	powerline-fonts &&
	chsh -s /usr/bin/zsh &&
	ln -s ${dothome}/zshrc ~/.zshrc &&
	mkdir -p ~/.ssh/ &&
	touch ~/.ssh/authorized_keys &&
	chmod 600 ~/.ssh/authorized_keys &&
	cat <<EOF >~/.ssh/authorized_keys
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPWi97DJG7FaVLj60B7hD/YOQBLUvOVTRlvM3BkL2t7C chief@beefdisciple.com
EOF
