#!/usr/bin/env bash

dothome=~/.dotfiles

yay -S \
	zsh \
	alsa-utils \
	zsh-completions \
	antibody \
	fzf \
	jq \
	bc \
	curl \
	ytmdl \
	polybar \
	kitty \
	kitty-terminfo \
	rofi \
	powerline-fonts

chsh -s /usr/bin/zsh && ln -s ${dothome}/zshrc ~/.zshrc

ln -s ${dothome}/ansiweatherrc ~/.ansiweatherrc

rm -f ~/.i3/config
ln -s ${dothome}/config/i3/config ~/.i3/config

rm -rf ~/.config/polybar
ln -s ${dothome}/config/polybar ~/.config/polybar

mkdir -p ~/.ssh/ &&
	touch ~/.ssh/authorized_keys &&
	chmod 600 ~/.ssh/authorized_keys &&
	cat <<EOF >~/.ssh/authorized_keys
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPWi97DJG7FaVLj60B7hD/YOQBLUvOVTRlvM3BkL2t7C chief@beefdisciple.com
EOF
