#!/usr/bin/env bash

# go-kubectx
git clone git@github.com:aca/go-kubectx.git /tmp/go-kubectx \
    && pushd /tmp/go-kubectx \
    && go install ./cmd/kubens \
    && go install ./cmd/kubectx \
    && popd \
    ; rm -rf /tmp/go-kubectx 
   
if [ $(uname) == "Linux" ]; then 
    sudo snap install bw
    
    cd /tmp && \
    curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    sudo mv ./kubectl /usr/local/bin 

else 
    brew install bitwarden-cli
fi